# Generated by Django 5.2.12 on 2026-04-04 22:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CableStandard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('voltage_rating', models.FloatField()),
                ('conductor_material', models.CharField(max_length=50)),
                ('insulation_type', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='CableInspection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result_image', models.ImageField(upload_to='inspection_images/')),
                ('defect_detected', models.BooleanField(default=False)),
                ('inspected_at', models.DateTimeField(auto_now_add=True)),
                ('cable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='core_cable_inspections', to='core.cablestandard')),
            ],
        ),
        migrations.CreateModel(
            name='DocumentAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_file', models.FileField(upload_to='documents/')),
                ('ocr_text', models.TextField()),
                ('analyzed_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='core_document_analyses', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
