# Generated by Django 5.2.12 on 2026-03-05 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DocumentAnalysis",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("document", models.FileField(upload_to="documents/uploads/")),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                ("original_filename", models.CharField(blank=True, max_length=255)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("READY", "Ready for Production"),
                            ("NOT_READY", "Not Ready"),
                            ("UNVERIFIABLE", "Unverifiable"),
                            ("ERROR", "Processing Error"),
                        ],
                        default="ERROR",
                        max_length=15,
                    ),
                ),
                ("cable_category", models.CharField(blank=True, max_length=100)),
                ("voltage_rating", models.CharField(blank=True, max_length=50)),
                ("current_rating", models.CharField(blank=True, max_length=50)),
                ("material", models.CharField(blank=True, max_length=100)),
                ("top_terms", models.JSONField(blank=True, default=list)),
                ("extracted_specs", models.JSONField(blank=True, default=dict)),
                ("validation_errors", models.JSONField(blank=True, default=list)),
                (
                    "processing_time",
                    models.FloatField(
                        blank=True, help_text="Processing time in seconds", null=True
                    ),
                ),
            ],
            options={
                "verbose_name": "Document Analysis",
                "verbose_name_plural": "Document Analyses",
                "ordering": ["-uploaded_at"],
            },
        ),
    ]
