# Generated by Django 5.2.12 on 2026-03-05 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CableInspection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="inspections/images/")),
                (
                    "result_image",
                    models.ImageField(
                        blank=True, null=True, upload_to="inspections/results/"
                    ),
                ),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PASS", "Pass"),
                            ("FAIL", "Fail"),
                            ("ERROR", "Error"),
                        ],
                        default="ERROR",
                        max_length=10,
                    ),
                ),
                ("diameter_mm", models.FloatField(blank=True, null=True)),
                ("defect_detected", models.BooleanField(default=False)),
                ("confidence_score", models.FloatField(blank=True, null=True)),
                (
                    "processing_time",
                    models.FloatField(
                        blank=True, help_text="Processing time in seconds", null=True
                    ),
                ),
                ("raw_data", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "verbose_name": "Cable Inspection",
                "verbose_name_plural": "Cable Inspections",
                "ordering": ["-uploaded_at"],
            },
        ),
    ]
