# Generated by Django 5.2.12 on 2026-04-04 22:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('inspections', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cableinspection',
            name='cable',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='inspections_cable_inspections', to='core.cablestandard'),
            preserve_default=False,
        ),
    ]
